id: I1184C0DE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:07:28+00:00'
last_modified: '2022-06-08T14:05:32.807910+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14498
  title: གསུང་འབུམ། འཇམ་དབྱངས་དོན་ཡོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B3F0:
      image_group_id: I1KG16170
      title: ''
      total_pages: 583
      order: 1
      base_file: B3F0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
