id: I1184C0DE
legacy_id: P010505
ocr_import_info:
  bdrc_scan_id: W1KG14498
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T12:03:58'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T06:54:35.576447+00:00'
last_modified: 2022-08-31 14:54:49.705206
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG14498
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG14498
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇམ་དབྱངས་དོན་ཡོད།
  author: སྔགས་ས་དགེ་བཤེས།
statistics:
  ocr_word_mean_confidence_index: 0.7124619310775827
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I1KG16170:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16170
      total_pages: 583
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16170.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7124619310775827
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
