id: P010505
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG14498
  title: གསུང་འབུམ། འཇམ་དབྱངས་དོན་ཡོད།
  author: ''
  volumes:
    86c39b7b702046a387473415779dfb7e:
      image_group_id: I1KG16170
      title: ''
      volume_number: 1
      total_pages: 583
      base_file: v001.txt
